<% branch_name = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '') %>
<% repository_name = `git rev-parse --show-toplevel`.split('/').last.strip %>

development:
  adapter: postgresql
  database: <%= repository_name %>_development
  host: localhost

test:
  adapter: postgresql
  database: <%= repository_name %>_test
  host: localhost

production:
  adapter: postgresql
  database: <%= repository_name %>_production
  host: localhost
